name: RecipeGen
version: '${project.version}'
main: me.vineer.recipegen.RecipeGen
api-version: 1.16
authors: [ Vineer ]
depend:
  - EconomyAPI
  - PlaceholderAPI
commands:
  recipemenu:
    description: test
    usage: /<command>
  addaction:
    description: add action to slot
    usage: /<command>
  createmenu:
    description: create menu
    usage: /<command>
  additem:
    description: adds item to menu
    usage: /<command>
  shop:
    description: shops
    usage: /<command>